version: '3'
services:
    memcached:
        image: memcached
        restart: always

    mongodb:
        image: library/mongo:3.4.9
        volumes:
           - ./data/mongodb:/data
        ports:
           - "27017:27017"
        restart: always
        privileged: true

    web:
        image: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/nginx/ssl"
            - "./web:/var/app"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - forum           
            - mysqldb
            - mongodb

    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "9991:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb

    mysqldb:
        image: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "32775:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"

        command: mysqld --sql_mode=""

    forum:
        build:
             context: ./fpm
        restart: always
        volumes:
            - "./web:/var/app"
        working_dir: /var/app/forum
